import it.unicam.cs.Flexchain.BlockchainUtils;
import java.util.List;
import java.util.ArrayList;

dialect  "mvel"
rule "Message_1pam53q"
when
  b : BlockchainUtils(b.getState("Message_1pam53q")==0)
then
 List names = new ArrayList();
    names.add("pizza");
 List values = new ArrayList();
    values.add(b.getSingleInput(0));
    b.setVariablesToContract(names, values, "Message_1pam53q");
 end

rule "Message_1ee2hc4"
when
  b : BlockchainUtils(b.getState("Message_1ee2hc4")==0, b.getState("Message_1pam53q")==2)
then
 List names = new ArrayList();
    names.add("confirmation");
 List values = new ArrayList();
    values.add(b.getSingleInput(0));
    b.setVariablesToContract(names, values, "Message_1ee2hc4");
 end

rule "Message_1kceupq"
when
  b : BlockchainUtils(b.getState("Message_1kceupq")==0, b.getState("Message_1ee2hc4")==2)
then
 List names = new ArrayList();
    names.add("money");
 List values = new ArrayList();
    values.add(b.getSingleInput(0));
    b.setVariablesToContract(names, values, "Message_1kceupq");
 end
